### ISSUE TITLE
`fd` is `fdfind` in Debian-based distros

### ISSUE THREAD

**Issue by shvchk** [danisztls/ephemeral#1]
https://github.com/danisztls/ephemeral/blob/646d04c726d984cae5b51a5bd3a950671bc1b803/ephemeral#L30

Maybe use something like
```sh
_fd=$(command -v fd | grep '^/' || command -v fdfind | grep '^/') # grep used to ignore aliases
#...
_chromium_root_dirs="$($_fd --type d \
#...
```

or add env var `$EPHEMERAL_FD`.

**Comment by danisztls** [comment]
Fixed by 9accc5ef085590e7c48af310b0d3b7971c60505f

Sorry about the delay.
