### ISSUE TITLE
Add option to use $XDG_CACHE_HOME instead of ephemeral storages like /run and /tmp

### ISSUE THREAD

**Issue by MurzNN** [danisztls/ephemeral#2]
Chromium really has a bug https://github.com/electron/electron/issues/8124 about storing temporary files in the permanent storage location. By the way, maybe make a link to it in the readme file?

And this project makes a really good thing to move those files outside of the permanent storage!

But! Cache files are not ephemeral files, they are temporary files, so the message of the project to use `$XDG_RUNTIME_DIR` and `tmpfs` for this is not quite right, from my point of view, and here are the reasons:

1. Tmpfs uses RAM and clears on each reboot, and the size of cache files can be quite large, it's not good to spend the RAM to store them! RAM is already heavily used by applications, and it's always the deficit of it in most of workstations.

2. Tmpfs clears on each restart of the system. This causes all cached files to disappear, so the application should recreate them on each start, which will spend additional startup time. So, all the benefits of "cache improve apps performance" disappear.

So, let's not confuse subjects, and still name those files as "cache", not as "ephemeral".

The best location for such files is the `$XDG_CACHE_HOME` directory, where all other applications store the cache files.

And the user should decide how to manage them, where to store them (in regular fs, tmpfs, separate partition, ext4 with disabled journaling, etc), how long store them, when to clear, etc. There are a lot of solutions to protect this universal directory for cache files from growing by cleaning up it on schedule, by the age of files (eg remove all files not accessed for 2 weeks), etc, so all users who care about this - will can use the same technic for Chromium cache files too.

And the `$XDG_RUNTIME_DIR` is a directory, intended for really runtime files (that should disappear after the application exits), not the cache files!

So, please, implement a build-in option to use  `$XDG_CACHE_HOME` directory for such files, instead of `$XDG_RUNTIME_DIR`. And maybe elaborate on this idea more in the readme file?

**Comment by danisztls** [comment]
The script reads the variable `$EPHEMERAL_DST` so `export $EPHEMERAL_DST=$XDG_CACHE_HOME` can be used to force the cache files to be moved there. But as it appears that this use case is more popular I will update the project to incorporate your suggestions.

Linking to tmpfs can be problematic but is not that bad, specially for machines with at least 16GB. It gives a small performance boost and minimizes writes to SSD. One issue though is that after a reboot the symlinks are left broken and the current code doesn't handle recovering the symlinks. Also running this on userspace at login as I did can lead to racing issues.

**Comment by danisztls** [comment]
Fixed by dbfee9a1d3a4dd87fb7e76c8afdb3d33b93a9db4
